Update logger dependency
googleforgames/agones pull request #2075
Opened 2021-04-24 16:15 UTC by shawticus

<!--  Thanks for sending a pull request!  Here are some tips for you:

**What type of PR is this?**
/kind cleanup

**What this PR does / Why we need it**:
Uses an ancient version the joonix logger which has the same API but a different constructor func. Updates the logger dependency and called NewFormatter instead of FluentdFormatter at line 37 of pkg/util/runtime.go

Benefit here is that it doesn't conflict with with other uses of the formatter.

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:
API is visible here: https://github.com/joonix/log
Change was here: https://github.com/joonix/log/commit/7b18c88b187dd428c41cb92f038fb0c9e68fa65a#diff-cd0d0ec8574c5b5d734dde8b50b74f5fff4d5cec387501cb0976ab8b0824c8a9
Code that needs to be changed in Agones is just this one call: https://github.com/googleforgames/agones/blob/094ec10ecce6fa5e5c206e74cbb8616d8712f480/pkg/util/runtime/runtime.go#L37

2021-04-24 16:17 UTC, shawticus commented
@googlebot I signed it!

2021-04-24 16:23 UTC, markmandel requested changes
Thanks for the PR, but unfortunately we can't accept it in it's current state.

While the upgrade to the logging library is a nice cleanup, the upgrades to grpc and related tooling is a much bigger change -- and I expect unrelated to the logging library update?

(There's also several other updates that are unrelated to logging in here. Might be worth either removing them or updating the PR title and description).

Out of curiosity - is there a reason for the logrus library update?

2021-04-24 16:23 UTC, markmandel commented on go.mod
> +	google.golang.org/grpc v1.36.1
Upgrading gRPC is a big change and I don't think would be not part of updating logging tooling? Please revert this change.

2021-04-24 16:23 UTC, markmandel commented on go.mod
> +	github.com/golang/protobuf v1.5.2
Not sure why we're upgrading protobuf. Seems like a big change for upgrading a logging library.

2021-04-24 18:10 UTC, closed without merging

2021-04-25 11:58 UTC, shawticus commented
@markmandel thanks for being nice. While I am feeling great about golang as a language I still am really confused by the package ecosystem still. I'm going to do some learning and reopen this PR when I know what I'm doing :)