Arbitrary counts lists 2716
googleforgames/agones pull request #2983
Opened 2023-02-21 21:51 UTC by igooch

**What type of PR is this?**
/kind feature

**What this PR does / Why we need it**:

**Which issue(s) this PR fixes**:
Working on #2716 

**Special notes for your reviewer**:

2023-02-22 21:48 UTC, gongmax commented on pkg/apis/agones/v1/gameserver.go
> +	}
Is this logic needed? Does `gs.Status.Counters = gs.Spec.Counters` simply work? I'm not sure how the deepcopy works but I'm taking `gs.applyEvictionStatus()` as reference.

2023-02-23 03:56 UTC, gongmax approved these changes
LGTM

2023-02-23 18:40 UTC, markmandel commented on pkg/apis/agones/v1/gameserver.go
> +type CounterStatus struct {
Since it's used in both Spec and Status, maybe the names should be `Counter` and `List` ? WDYT?

2023-02-23 21:27 UTC, markmandel requested changes
Just marking as request changes, since I'd like to get my comments reviewed before merging.

2023-02-23 23:44 UTC, markmandel approved these changes
LGTM! (Assuming everything passes 👍🏻 )

2023-02-24 19:25 UTC, markmandel commented
Ruh roh. Lots of conflicts. Sorry - that was my CRD work.

2023-02-27 19:35 UTC, merged