Set timeout duration as optional argument
googleforgames/agones pull request #4050
Opened 2024-11-26 08:25 UTC by AndreasWintherMoen

**What type of PR is this?**

/kind cleanup

**What this PR does / Why we need it**:

Just a small change to add an optional _timeoutSeconds_ argument instead of a hard-coded value in Connect method in Unity SDK. This allows users to set a custom timeout duration if they have a very specific setup that requires it. The default timeout is 30 seconds to ensure backward compatibility.

2024-11-26 11:46 UTC, AndreasWintherMoen commented
Fixed CLA. Not sure what other failing check is caused by.

2024-11-26 22:05 UTC, igooch commented
/gcbrun

2024-11-27 17:05 UTC, gongmax commented
Hi @AndreasWintherMoen , thanks for contribution! Would you mind add some description to the doc [here](https://github.com/googleforgames/agones/blob/edde3c39eb5c57dad19a8fd51fd608996e8417b5/site/content/en/docs/Guides/Client%20SDKs/unity.md?plain=1#L84-L89) for the change? Thanks!

2024-12-02 16:36 UTC, igooch commented
/gcbrun

2024-12-06 22:14 UTC, igooch approved these changes
LGTM

2024-12-06 22:15 UTC, igooch commented
/gcbrun

2024-12-06 22:54 UTC, igooch requested changes

2024-12-06 22:54 UTC, igooch commented on site/content/en/docs/Guides/Client SDKs/unity.md
> +By default, this will wait for up to 30 seconds if the SDK server has not yet started and the connection cannot be made. You can specify an optional timeout duration argument to the method, e.g., Con
Should add feature expiry around the deleted lines, and publish version around the new lines.

```
{{% feature expiryVersion="1.46.0" %}}
{{% /feature %}}
```

```
publish='{{% feature publishVersion="1.46.0" %}}'
{{% /feature %}}
```

2025-01-08 02:01 UTC, markmandel commented
Super late to the party on this PR, but I'll ask the question: _why_? 😄 we've used 30s everywhere else, seems strange to deviate in one place without a pretty strong reason.

2025-03-11 19:59 UTC, gongmax commented
Closing now since no active engagement for a while.

2025-03-11 19:59 UTC, closed without merging